/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import CSV.HelperView;
import Modelo.Cliente;
import Modelo.ClienteDAO;
import Modelo.Conexion;
import Modelo.Pelicula;
import dao.ClubDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danic
 */
public class Vista1 extends javax.swing.JFrame {
       private Conexion con;
       private List<Cliente> listaClientes;
       private ClienteDAO clienteDAO;
       private DefaultTableModel tabla;

    
  
    /**
     * Creates new form Vista
     */
    public Vista1() throws SQLException {
        con = new Conexion();
        clienteDAO = new ClienteDAO();
       
        setTitle("Proyecto Final Programacion");
        initComponents();
        
        tabla = new DefaultTableModel();
        tabla.addColumn("Clientes");
        tabla.addColumn("Peliculas");
        tabla.addColumn("Alquiladas");
        
        jTable1.setModel(tabla);
        
        listaClientes = clienteDAO.obtenerCliente();
        
/*
        for (Cliente listaCliente : listaClientes) {
        tabla.addColumn(listaCliente.getDni());
        tabla.addColumn(listaCliente.getNombre());
        
        }*/
        
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelCLIENTE = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNOMBRE = new javax.swing.JLabel();
        jLabelAPELLIDOS = new javax.swing.JLabel();
        jLabel5EDAD = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNOMBRE = new javax.swing.JTextField();
        jTextFieldAPELLIDOS = new javax.swing.JTextField();
        jTextFieldEDAD = new javax.swing.JTextField();
        jLabelPELICULA = new javax.swing.JLabel();
        jLabelCODIGO = new javax.swing.JLabel();
        jLabelTITULO = new javax.swing.JLabel();
        jLabelAUTOR = new javax.swing.JLabel();
        jLabelANIO = new javax.swing.JLabel();
        jLabeGENERO = new javax.swing.JLabel();
        jTextFieldCODIGO = new javax.swing.JTextField();
        jTextFieldTITULO = new javax.swing.JTextField();
        jTextFieldAUTOR = new javax.swing.JTextField();
        jTextFielANIO = new javax.swing.JTextField();
        jTextFieldGENERO = new javax.swing.JTextField();
        jLabelALQUILER = new javax.swing.JLabel();
        jLabelFECHAALQUILADA = new javax.swing.JLabel();
        jTextFieldFECHAALQUILADA = new javax.swing.JTextField();
        jLabelFECHADEVOLUCION = new javax.swing.JLabel();
        jTextFieldFECHADEVOLUCION = new javax.swing.JTextField();
        jLabelDNICLIENTE = new javax.swing.JLabel();
        jTextFieldDNICLIENTE = new javax.swing.JTextField();
        jLabelCODPELICULA = new javax.swing.JLabel();
        jTextFieldCODPELICULA = new javax.swing.JTextField();
        jButtonBORRAR = new javax.swing.JButton();
        jButtonANADIR = new javax.swing.JButton();
        jButtonLIMPIAR = new javax.swing.JButton();
        jButtonACTUALIZAR = new javax.swing.JButton();
        jScrollPaneLISTA = new javax.swing.JScrollPane();
        jTextArea1CAJA = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelCLIENTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCLIENTE.setText("Cliente");

        jLabelDNI.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelDNI.setText("Dni");

        jLabelNOMBRE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelNOMBRE.setText("Nombre");

        jLabelAPELLIDOS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelAPELLIDOS.setText("Apellidos");

        jLabel5EDAD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5EDAD.setText("Edad");

        jLabelPELICULA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPELICULA.setText("Pelicula");

        jLabelCODIGO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCODIGO.setText("Codigo");

        jLabelTITULO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelTITULO.setText("Titulo");

        jLabelAUTOR.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelAUTOR.setText("Autor");

        jLabelANIO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelANIO.setText("Año");

        jLabeGENERO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabeGENERO.setText("Genero");

        jLabelALQUILER.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelALQUILER.setText("Alquiler");

        jLabelFECHAALQUILADA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFECHAALQUILADA.setText("Fecha alquilada");

        jLabelFECHADEVOLUCION.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFECHADEVOLUCION.setText("Fecha devolucion");

        jLabelDNICLIENTE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelDNICLIENTE.setText("DniCliente");

        jTextFieldDNICLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNICLIENTEActionPerformed(evt);
            }
        });

        jLabelCODPELICULA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCODPELICULA.setText("CodPelicula");

        jButtonBORRAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBORRAR.setText("Borrar");

        jButtonANADIR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonANADIR.setText("Añadir");
        jButtonANADIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonANADIRMouseClicked(evt);
            }
        });
        jButtonANADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANADIRActionPerformed(evt);
            }
        });

        jButtonLIMPIAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonLIMPIAR.setText("Limpiar");
        jButtonLIMPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLIMPIARMouseClicked(evt);
            }
        });

        jButtonACTUALIZAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonACTUALIZAR.setText("Actualizar");
        jButtonACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACTUALIZARActionPerformed(evt);
            }
        });

        jTextArea1CAJA.setColumns(20);
        jTextArea1CAJA.setRows(5);
        jScrollPaneLISTA.setViewportView(jTextArea1CAJA);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAPELLIDOS)
                                    .addComponent(jLabel5EDAD)
                                    .addComponent(jLabelNOMBRE)
                                    .addComponent(jLabelDNI)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCODIGO)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelTITULO)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelANIO)
                                            .addComponent(jLabelAUTOR)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabeGENERO)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFielANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonANADIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(65, 65, 65)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonBORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonLIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(87, 87, 87))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelFECHAALQUILADA)
                                    .addGap(30, 30, 30)
                                    .addComponent(jTextFieldFECHAALQUILADA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelFECHADEVOLUCION)
                                        .addComponent(jLabelDNICLIENTE)
                                        .addComponent(jLabelCODPELICULA))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldFECHADEVOLUCION, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldDNICLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCODPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(104, 104, 104)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelALQUILER)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPaneLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPELICULA)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCLIENTE)
                    .addComponent(jLabelALQUILER))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFECHAALQUILADA)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDNI)
                        .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFECHAALQUILADA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFECHADEVOLUCION, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNOMBRE)
                        .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFECHADEVOLUCION)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDNICLIENTE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAPELLIDOS)
                        .addComponent(jTextFieldAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDNICLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5EDAD)
                    .addComponent(jTextFieldEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCODPELICULA)
                    .addComponent(jTextFieldCODPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabelPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCODIGO)
                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonANADIR)
                    .addComponent(jButtonBORRAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTITULO)
                    .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonACTUALIZAR)
                    .addComponent(jButtonLIMPIAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAUTOR)
                            .addComponent(jTextFieldAUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelANIO)
                            .addComponent(jTextFielANIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeGENERO)
                            .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Clientes", "Peliculas", "Alquiladas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("< 10");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<< 20");

        jButton7.setText("10 >");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("20 >>");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Clientes");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Peliculas");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Alquiladas");

        jButton9.setText("< 10");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("< 10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("10 >");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("10 >");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("<< 20");

        jButton14.setText("20 >>");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("<< 20");

        jButton16.setText("20 >>");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel17)
                .addGap(156, 156, 156)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(77, 77, 77))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(85, 85, 85)
                        .addComponent(jButton13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton15)
                    .addComponent(jButton10))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16)
                    .addComponent(jButton12))
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton6)
                    .addComponent(jButton14)
                    .addComponent(jButton13)
                    .addComponent(jButton16)
                    .addComponent(jButton15))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Opcional", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setText("Creditos");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDNICLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNICLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNICLIENTEActionPerformed

    private void jButtonANADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANADIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonANADIRActionPerformed

    private void jButtonACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACTUALIZARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonACTUALIZARActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButtonANADIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonANADIRMouseClicked
        // TODO add your handling code here:
        
     //Cliente
     String dni = jTextFieldDNI.getText();
     String nombre = jTextFieldNOMBRE.getText();
     String apellidos = jTextFieldAPELLIDOS.getText();
     String edad = jTextFieldEDAD.getText();
     
     System.out.println("Prueba anadir");
     
     int contenido = 0;
     
        if(dni.isEmpty() || nombre.isEmpty() || apellidos.isEmpty() || edad.isEmpty() ){
        contenido = 1;
    }
    if (contenido == 1){    
        
     switch (contenido) {
         
        case 1:
         if(dni.isEmpty()){
         JOptionPane.showConfirmDialog(null, "Por favor rellene Cliente: DNI", "Añadir", YES_NO_OPTION, QUESTION_MESSAGE);
         }
         
         case 2:
         if(nombre.isEmpty()){
         JOptionPane.showConfirmDialog(null, "Por favor rellene Cliente: Nombre", "Añadir", YES_NO_OPTION, QUESTION_MESSAGE);
         }
         
         case 3:
         if(apellidos.isEmpty()){
         JOptionPane.showConfirmDialog(null, "Por favor rellene Cliente Apellidos", "Añadir", YES_NO_OPTION, QUESTION_MESSAGE);
         }
         
         case 4:
         if(edad.isEmpty()){
         JOptionPane.showConfirmDialog(null, "Por favor rellene Cliente Edad", "Añadir", YES_NO_OPTION, QUESTION_MESSAGE);
         }
         
        break;
           
        }
     
    }else
 
      if(!dni.isEmpty()){
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de añadir el usuario", "Añadir", YES_NO_OPTION, QUESTION_MESSAGE);
                if (respuesta == YES_NO_OPTION){
                    System.out.println("EXITO11");
                    Cliente c = new Cliente(dni, nombre, apellidos, edad);
                     System.out.println("EXITO22");
                    clienteDAO.anadirCliente(c);
                     System.out.println("EXITO33");
                   // clienteDAO.anadirClienteLista(c);
                     System.out.println("EXITO44");
                    JOptionPane.showMessageDialog(null, "Cliente añadido correctamente", "Añadir", INFORMATION_MESSAGE);
                   
                }else JOptionPane.showMessageDialog(null, "No se puede añadir un Cliente sin el DNI", "Añadir", INFORMATION_MESSAGE);
        }
    
    
    }//GEN-LAST:event_jButtonANADIRMouseClicked

    private void jButtonLIMPIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLIMPIARMouseClicked
        // TODO add your handling code here:
        jTextFieldDNI.setText("");
        jTextFieldNOMBRE.setText("");
        jTextFieldAPELLIDOS.setText("");
        jTextFieldEDAD.setText("");
        jTextFieldCODIGO.setText("");
        jTextFieldTITULO.setText("");
        jTextFieldAUTOR.setText("");
        jTextFielANIO.setText("");
        jTextFieldGENERO.setText("");
        jTextFieldFECHAALQUILADA.setText("");
        jTextFieldFECHADEVOLUCION.setText("");
        jTextFieldDNICLIENTE.setText("");
        jTextFieldCODPELICULA.setText("");
        jTextArea1CAJA.setText("");
        
    }//GEN-LAST:event_jButtonLIMPIARMouseClicked

   public void FechaActual(){
       
      Calendar fecha = new GregorianCalendar();
      int anio = fecha.get(Calendar.YEAR);
      int mes = fecha.get(Calendar.MONTH);
      int dia = fecha.get(Calendar.DAY_OF_MONTH);
      
      String fechaActual = dia + "/" + (mes+1) + "/" + anio;
      jTextFieldFECHAALQUILADA.setText(fechaActual);
   }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    System.out.println("Prueba de vista");
                    new Vista1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Vista1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonACTUALIZAR;
    private javax.swing.JButton jButtonANADIR;
    private javax.swing.JButton jButtonBORRAR;
    private javax.swing.JButton jButtonLIMPIAR;
    private javax.swing.JLabel jLabeGENERO;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5EDAD;
    private javax.swing.JLabel jLabelALQUILER;
    private javax.swing.JLabel jLabelANIO;
    private javax.swing.JLabel jLabelAPELLIDOS;
    private javax.swing.JLabel jLabelAUTOR;
    private javax.swing.JLabel jLabelCLIENTE;
    private javax.swing.JLabel jLabelCODIGO;
    private javax.swing.JLabel jLabelCODPELICULA;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDNICLIENTE;
    private javax.swing.JLabel jLabelFECHAALQUILADA;
    private javax.swing.JLabel jLabelFECHADEVOLUCION;
    private javax.swing.JLabel jLabelNOMBRE;
    private javax.swing.JLabel jLabelPELICULA;
    private javax.swing.JLabel jLabelTITULO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneLISTA;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1CAJA;
    private javax.swing.JTextField jTextFielANIO;
    private javax.swing.JTextField jTextFieldAPELLIDOS;
    private javax.swing.JTextField jTextFieldAUTOR;
    private javax.swing.JTextField jTextFieldCODIGO;
    private javax.swing.JTextField jTextFieldCODPELICULA;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDNICLIENTE;
    private javax.swing.JTextField jTextFieldEDAD;
    private javax.swing.JTextField jTextFieldFECHAALQUILADA;
    private javax.swing.JTextField jTextFieldFECHADEVOLUCION;
    private javax.swing.JTextField jTextFieldGENERO;
    private javax.swing.JTextField jTextFieldNOMBRE;
    private javax.swing.JTextField jTextFieldTITULO;
    // End of variables declaration//GEN-END:variables

}
