/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.AlquilerDAO;
import Modelo.Cliente;
import Modelo.ClienteDAO;
import Modelo.Conexion;
import Modelo.PeliculaDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Sierra Raez
 */
public class Vista extends javax.swing.JFrame {
      // private Conexion14 con;
       private ClienteDAO clienteDAO;
       private Cliente c;
       private PeliculaDAO peliculaDAO;
    //   private List<Cliente14> listaClientes;
       private DefaultTableModel tabla = new DefaultTableModel();
       private DefaultListModel l1 = new DefaultListModel();
       private DefaultListModel l2 = new DefaultListModel();
       private DefaultListModel l3 = new DefaultListModel();

    /**
     * Creates new form Vista
     */
    public Vista() throws SQLException {
     //   con = new Conexion14();
       
        setTitle("Proyecto Final Programacion");
        setVisible(true);
        initComponents();
           
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelCLIENTE = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNOMBRE = new javax.swing.JLabel();
        jLabelAPELLIDOS = new javax.swing.JLabel();
        jLabel5EDAD = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNOMBRE = new javax.swing.JTextField();
        jTextFieldAPELLIDOS = new javax.swing.JTextField();
        jTextFieldEDAD = new javax.swing.JTextField();
        jLabelPELICULA = new javax.swing.JLabel();
        jLabelCODIGO = new javax.swing.JLabel();
        jLabelTITULO = new javax.swing.JLabel();
        jLabelAUTOR = new javax.swing.JLabel();
        jLabelANIO = new javax.swing.JLabel();
        jLabeGENERO = new javax.swing.JLabel();
        jTextFieldCODIGO = new javax.swing.JTextField();
        jTextFieldTITULO = new javax.swing.JTextField();
        jTextFieldDIRECTOR = new javax.swing.JTextField();
        jTextFielANIO = new javax.swing.JTextField();
        jTextFieldGENERO = new javax.swing.JTextField();
        jLabelALQUILER = new javax.swing.JLabel();
        jLabelFECHAALQUILADA = new javax.swing.JLabel();
        jTextFieldFECHAALQUILADA = new javax.swing.JTextField();
        jLabelFECHADEVOLUCION = new javax.swing.JLabel();
        jTextFieldFECHADEVOLUCION = new javax.swing.JTextField();
        jLabelDNICLIENTE = new javax.swing.JLabel();
        jTextFieldDNICLIENTE = new javax.swing.JTextField();
        jLabelCODPELICULA = new javax.swing.JLabel();
        jTextFieldCODPELICULA = new javax.swing.JTextField();
        jButtonBORRAR = new javax.swing.JButton();
        jButtonANADIR = new javax.swing.JButton();
        jButtonLIMPIAR = new javax.swing.JButton();
        jButtonACTUALIZAR = new javax.swing.JButton();
        jScrollPaneLISTA = new javax.swing.JScrollPane();
        jTextArea1CAJA = new javax.swing.JTextArea();
        jButtonACTIVARALQUILER = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldBUSCAR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList<>();
        jLabel1ClientesOpcional = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPeliculas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAlquileres = new javax.swing.JList<>();
        jLabel2PeliculasOpcional = new javax.swing.JLabel();
        jLabel3AlquileresOpcional = new javax.swing.JLabel();
        jButton3VolcarAlquileres = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelCLIENTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCLIENTE.setText("Cliente");

        jLabelDNI.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelDNI.setText("Dni");

        jLabelNOMBRE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelNOMBRE.setText("Nombre");

        jLabelAPELLIDOS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelAPELLIDOS.setText("Apellidos");

        jLabel5EDAD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5EDAD.setText("Edad");

        jLabelPELICULA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPELICULA.setText("Pelicula");

        jLabelCODIGO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCODIGO.setText("Codigo");

        jLabelTITULO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelTITULO.setText("Titulo");

        jLabelAUTOR.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelAUTOR.setText("Autor");

        jLabelANIO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelANIO.setText("Año");

        jLabeGENERO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabeGENERO.setText("Genero");

        jLabelALQUILER.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelALQUILER.setText("Alquiler");

        jLabelFECHAALQUILADA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFECHAALQUILADA.setText("Fecha alquilada");

        jLabelFECHADEVOLUCION.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFECHADEVOLUCION.setText("Fecha devolucion");

        jLabelDNICLIENTE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelDNICLIENTE.setText("DniCliente");

        jTextFieldDNICLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNICLIENTEActionPerformed(evt);
            }
        });

        jLabelCODPELICULA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCODPELICULA.setText("CodPelicula");

        jButtonBORRAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBORRAR.setText("Borrar");
        jButtonBORRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBORRARMouseClicked(evt);
            }
        });

        jButtonANADIR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonANADIR.setText("Añadir");
        jButtonANADIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonANADIRMouseClicked(evt);
            }
        });
        jButtonANADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANADIRActionPerformed(evt);
            }
        });

        jButtonLIMPIAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonLIMPIAR.setText("Limpiar");
        jButtonLIMPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLIMPIARMouseClicked(evt);
            }
        });

        jButtonACTUALIZAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonACTUALIZAR.setText("Actualizar");
        jButtonACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACTUALIZARActionPerformed(evt);
            }
        });

        jTextArea1CAJA.setColumns(20);
        jTextArea1CAJA.setRows(5);
        jScrollPaneLISTA.setViewportView(jTextArea1CAJA);

        jButtonACTIVARALQUILER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonACTIVARALQUILER.setText("Activar");
        jButtonACTIVARALQUILER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonACTIVARALQUILERMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAPELLIDOS)
                                    .addComponent(jLabel5EDAD)
                                    .addComponent(jLabelNOMBRE)
                                    .addComponent(jLabelDNI)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCODIGO)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelTITULO)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelANIO)
                                            .addComponent(jLabelAUTOR)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabeGENERO)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDIRECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFielANIO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelFECHAALQUILADA)
                                    .addGap(30, 30, 30)
                                    .addComponent(jTextFieldFECHAALQUILADA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelFECHADEVOLUCION)
                                        .addComponent(jLabelDNICLIENTE)
                                        .addComponent(jLabelCODPELICULA))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldFECHADEVOLUCION, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldDNICLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCODPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(104, 104, 104))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonANADIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(65, 65, 65)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonBORRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonLIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonACTIVARALQUILER))
                            .addGap(87, 87, 87)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelALQUILER)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPaneLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPELICULA)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCLIENTE)
                    .addComponent(jLabelALQUILER))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFECHAALQUILADA)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDNI)
                        .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFECHAALQUILADA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFECHADEVOLUCION)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNOMBRE)
                        .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFECHADEVOLUCION)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDNICLIENTE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAPELLIDOS)
                        .addComponent(jTextFieldAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDNICLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5EDAD)
                    .addComponent(jTextFieldEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCODPELICULA)
                    .addComponent(jTextFieldCODPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonACTIVARALQUILER)
                .addGap(12, 12, 12)
                .addComponent(jLabelPELICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCODIGO)
                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonANADIR)
                    .addComponent(jButtonBORRAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTITULO)
                    .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonACTUALIZAR)
                    .addComponent(jButtonLIMPIAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAUTOR)
                            .addComponent(jTextFieldDIRECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelANIO)
                            .addComponent(jTextFielANIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeGENERO)
                            .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Clientes", "Peliculas", "Alquiladas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextFieldBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBUSCARActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BUSCAR");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Borrar");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nombre Cliente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Titulo Pelicula:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButtonOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonOK.setText("OK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", jPanel3);

        jScrollPane2.setViewportView(jListClientes);

        jLabel1ClientesOpcional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1ClientesOpcional.setText("Clientes");

        jScrollPane3.setViewportView(jListPeliculas);

        jScrollPane4.setViewportView(jListAlquileres);

        jLabel2PeliculasOpcional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2PeliculasOpcional.setText("Peliculas");

        jLabel3AlquileresOpcional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3AlquileresOpcional.setText("Alquileres");

        jButton3VolcarAlquileres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3VolcarAlquileres.setText("Volcar");
        jButton3VolcarAlquileres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3VolcarAlquileresMouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Actualizar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1ClientesOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jLabel2PeliculasOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jLabel3AlquileresOpcional)
                .addGap(74, 74, 74))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton3VolcarAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1ClientesOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2PeliculasOpcional)
                    .addComponent(jLabel3AlquileresOpcional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3VolcarAlquileres)
                    .addComponent(jButton3))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opcional", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setText("Creditos");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDNICLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNICLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNICLIENTEActionPerformed

    private void jButtonANADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANADIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonANADIRActionPerformed

    private void jButtonACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACTUALIZARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonACTUALIZARActionPerformed

    private void jButtonANADIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonANADIRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonANADIRMouseClicked
    /*
    public Conexion14 getCon() {
        return con;
    }
*//*
    public void setCon(Conexion14 con) {
        this.con = con;
    }
*/
    public DefaultListModel getL1() {
        return l1;
    }

    public DefaultListModel getL2() {
        return l2;
    }

    public DefaultListModel getL3() {
        return l3;
    }
    
    public JList<String> getjListAlquileres() {
        return jListAlquileres;
    }

    public JList<String> getjListClientes() {
        return jListClientes;
    }

    public JList<String> getjListPeliculas() {
        return jListPeliculas;
    }
    
    
/*
    public List<Cliente14> getListaClientes() {
        return listaClientes;
    }

    public void setListaClientes(List<Cliente14> listaClientes) {
        this.listaClientes = listaClientes;
    }
*/
    public ClienteDAO getClienteDAO() {
        return clienteDAO;
    }

    public void setClienteDAO(ClienteDAO clienteDAO) {
        this.clienteDAO = clienteDAO;
    }

    public PeliculaDAO getPeliculaDAO() {
        return peliculaDAO;
    }

    public void setPeliculaDAO(PeliculaDAO peliculaDAO) {
        this.peliculaDAO = peliculaDAO;
    }
    
    public DefaultTableModel getTabla() {
        return tabla;
    }

    public void setTabla(DefaultTableModel tabla) {
        this.tabla = tabla;
    }

    public JButton getjButtonACTUALIZAR() {
        return jButtonACTUALIZAR;
    }

    public void setjButtonACTUALIZAR(JButton jButtonACTUALIZAR) {
        this.jButtonACTUALIZAR = jButtonACTUALIZAR;
    }

    public JButton getjButtonANADIR() {
        return jButtonANADIR;
    }

    public JButton getjButton3VolcarAlquileres() {
        return jButton3VolcarAlquileres;
    }
    
    

    public void setjButtonANADIR(JButton jButtonANADIR) {
        this.jButtonANADIR = jButtonANADIR;
    }

    public JButton getjButtonBORRAR() {
        return jButtonBORRAR;
    }

    public JButton getjButtonACTIVARALQUILER() {
        return jButtonACTIVARALQUILER;
    }

    public void setjButtonBORRAR(JButton jButtonBORRAR) {
        this.jButtonBORRAR = jButtonBORRAR;
    }

    public JButton getjButtonLIMPIAR() {
        return jButtonLIMPIAR;
    }

    public void setjButtonLIMPIAR(JButton jButtonLIMPIAR) {
        this.jButtonLIMPIAR = jButtonLIMPIAR;
    }

    public JLabel getjLabeGENERO() {
        return jLabeGENERO;
    }

    public void setjLabeGENERO(JLabel jLabeGENERO) {
        this.jLabeGENERO = jLabeGENERO;
    }

    public JLabel getjLabel5EDAD() {
        return jLabel5EDAD;
    }

    public void setjLabel5EDAD(JLabel jLabel5EDAD) {
        this.jLabel5EDAD = jLabel5EDAD;
    }

    public JLabel getjLabelALQUILER() {
        return jLabelALQUILER;
    }

    public void setjLabelALQUILER(JLabel jLabelALQUILER) {
        this.jLabelALQUILER = jLabelALQUILER;
    }

    public JLabel getjLabelANIO() {
        return jLabelANIO;
    }

    public void setjLabelANIO(JLabel jLabelANIO) {
        this.jLabelANIO = jLabelANIO;
    }

    public JLabel getjLabelAPELLIDOS() {
        return jLabelAPELLIDOS;
    }

    public void setjLabelAPELLIDOS(JLabel jLabelAPELLIDOS) {
        this.jLabelAPELLIDOS = jLabelAPELLIDOS;
    }

    public JLabel getjLabelAUTOR() {
        return jLabelAUTOR;
    }

    public void setjLabelAUTOR(JLabel jLabelAUTOR) {
        this.jLabelAUTOR = jLabelAUTOR;
    }

    public JLabel getjLabelCLIENTE() {
        return jLabelCLIENTE;
    }

    public void setjLabelCLIENTE(JLabel jLabelCLIENTE) {
        this.jLabelCLIENTE = jLabelCLIENTE;
    }

    public JLabel getjLabelCODIGO() {
        return jLabelCODIGO;
    }

    public void setjLabelCODIGO(JLabel jLabelCODIGO) {
        this.jLabelCODIGO = jLabelCODIGO;
    }

    public JLabel getjLabelCODPELICULA() {
        return jLabelCODPELICULA;
    }

    public void setjLabelCODPELICULA(JLabel jLabelCODPELICULA) {
        this.jLabelCODPELICULA = jLabelCODPELICULA;
    }

    public JLabel getjLabelDNI() {
        return jLabelDNI;
    }

    public void setjLabelDNI(JLabel jLabelDNI) {
        this.jLabelDNI = jLabelDNI;
    }

    public JLabel getjLabelDNICLIENTE() {
        return jLabelDNICLIENTE;
    }

    public void setjLabelDNICLIENTE(JLabel jLabelDNICLIENTE) {
        this.jLabelDNICLIENTE = jLabelDNICLIENTE;
    }

    public JLabel getjLabelFECHAALQUILADA() {
        return jLabelFECHAALQUILADA;
    }

    public void setjLabelFECHAALQUILADA(JLabel jLabelFECHAALQUILADA) {
        this.jLabelFECHAALQUILADA = jLabelFECHAALQUILADA;
    }

    public JLabel getjLabelFECHADEVOLUCION() {
        return jLabelFECHADEVOLUCION;
    }

    public void setjLabelFECHADEVOLUCION(JLabel jLabelFECHADEVOLUCION) {
        this.jLabelFECHADEVOLUCION = jLabelFECHADEVOLUCION;
    }

    public JLabel getjLabelNOMBRE() {
        return jLabelNOMBRE;
    }

    public void setjLabelNOMBRE(JLabel jLabelNOMBRE) {
        this.jLabelNOMBRE = jLabelNOMBRE;
    }

    public JLabel getjLabelPELICULA() {
        return jLabelPELICULA;
    }

    public void setjLabelPELICULA(JLabel jLabelPELICULA) {
        this.jLabelPELICULA = jLabelPELICULA;
    }

    public JLabel getjLabelTITULO() {
        return jLabelTITULO;
    }

    public void setjLabelTITULO(JLabel jLabelTITULO) {
        this.jLabelTITULO = jLabelTITULO;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPaneLISTA() {
        return jScrollPaneLISTA;
    }

    public void setjScrollPaneLISTA(JScrollPane jScrollPaneLISTA) {
        this.jScrollPaneLISTA = jScrollPaneLISTA;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextArea getjTextArea1CAJA() {
        return jTextArea1CAJA;
    }

    public void setjTextArea1CAJA(JTextArea jTextArea1CAJA) {
        this.jTextArea1CAJA = jTextArea1CAJA;
    }

    public JTextField getjTextFielANIO() {
        return jTextFielANIO;
    }

    public void setjTextFielANIO(JTextField jTextFielANIO) {
        this.jTextFielANIO = jTextFielANIO;
    }

    public JTextField getjTextFieldAPELLIDOS() {
        return jTextFieldAPELLIDOS;
    }

    public void setjTextFieldAPELLIDOS(JTextField jTextFieldAPELLIDOS) {
        this.jTextFieldAPELLIDOS = jTextFieldAPELLIDOS;
    }

    public JTextField getjTextFieldCODIGO() {
        return jTextFieldCODIGO;
    }

    public void setjTextFieldCODIGO(JTextField jTextFieldCODIGO) {
        this.jTextFieldCODIGO = jTextFieldCODIGO;
    }

    public JTextField getjTextFieldCODPELICULA() {
        return jTextFieldCODPELICULA;
    }

    public void setjTextFieldCODPELICULA(JTextField jTextFieldCODPELICULA) {
        this.jTextFieldCODPELICULA = jTextFieldCODPELICULA;
    }

    public JTextField getjTextFieldDIRECTOR() {
        return jTextFieldDIRECTOR;
    }

    public void setjTextFieldDIRECTOR(JTextField jTextFieldDIRECTOR) {
        this.jTextFieldDIRECTOR = jTextFieldDIRECTOR;
    }

    public JTextField getjTextFieldDNI() {
        return jTextFieldDNI;
    }

    public void setjTextFieldDNI(JTextField jTextFieldDNI) {
        this.jTextFieldDNI = jTextFieldDNI;
    }

    public JTextField getjTextFieldDNICLIENTE() {
        return jTextFieldDNICLIENTE;
    }

    public void setjTextFieldDNICLIENTE(JTextField jTextFieldDNICLIENTE) {
        this.jTextFieldDNICLIENTE = jTextFieldDNICLIENTE;
    }

    public JTextField getjTextFieldEDAD() {
        return jTextFieldEDAD;
    }

    public void setjTextFieldEDAD(JTextField jTextFieldEDAD) {
        this.jTextFieldEDAD = jTextFieldEDAD;
    }

    public JTextField getjTextFieldFECHAALQUILADA() {
        return jTextFieldFECHAALQUILADA;
    }

    public void setjTextFieldFECHAALQUILADA(JTextField jTextFieldFECHAALQUILADA) {
        this.jTextFieldFECHAALQUILADA = jTextFieldFECHAALQUILADA;
    }

    public JTextField getjTextFieldFECHADEVOLUCION() {
        return jTextFieldFECHADEVOLUCION;
    }

    public void setjTextFieldFECHADEVOLUCION(JTextField jTextFieldFECHADEVOLUCION) {
        this.jTextFieldFECHADEVOLUCION = jTextFieldFECHADEVOLUCION;
    }

    public JTextField getjTextFieldGENERO() {
        return jTextFieldGENERO;
    }

    public void setjTextFieldGENERO(JTextField jTextFieldGENERO) {
        this.jTextFieldGENERO = jTextFieldGENERO;
    }

    public JTextField getjTextFieldNOMBRE() {
        return jTextFieldNOMBRE;
    }

    public void setjTextFieldNOMBRE(JTextField jTextFieldNOMBRE) {
        this.jTextFieldNOMBRE = jTextFieldNOMBRE;
    }

    public JTextField getjTextFieldTITULO() {
        return jTextFieldTITULO;
    }

    public void setjTextFieldTITULO(JTextField jTextFieldTITULO) {
        this.jTextFieldTITULO = jTextFieldTITULO;
    }

    private void jButtonLIMPIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLIMPIARMouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jButtonLIMPIARMouseClicked

    private void jButton3VolcarAlquileresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3VolcarAlquileresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3VolcarAlquileresMouseClicked

    private void jButtonACTIVARALQUILERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonACTIVARALQUILERMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonACTIVARALQUILERMouseClicked

    private void jTextFieldBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBUSCARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBUSCARActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonBORRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBORRARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBORRARMouseClicked

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista114.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista114.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista114.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista114.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Vista114 vista = new Vista114();
                    vista.setVisible(true);
                    ClienteDAO14 cliente = new ClienteDAO14();
                    PeliculaDAO14 pelicula = new PeliculaDAO14();
                    AlquilerDAO14 alquiler = new AlquilerDAO14();
                    
                    Controlador14 c = new Controlador14(vista, cliente, pelicula, alquiler);
                    c.fechaActual();
                    c.tabla();
                    c.rellenaCliente();
                    c.rellenaPelicula();
                    c.desactivarCamposAlquiler();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Vista114.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3VolcarAlquileres;
    private javax.swing.JButton jButtonACTIVARALQUILER;
    private javax.swing.JButton jButtonACTUALIZAR;
    private javax.swing.JButton jButtonANADIR;
    private javax.swing.JButton jButtonBORRAR;
    private javax.swing.JButton jButtonLIMPIAR;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabeGENERO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1ClientesOpcional;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2PeliculasOpcional;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3AlquileresOpcional;
    private javax.swing.JLabel jLabel5EDAD;
    private javax.swing.JLabel jLabelALQUILER;
    private javax.swing.JLabel jLabelANIO;
    private javax.swing.JLabel jLabelAPELLIDOS;
    private javax.swing.JLabel jLabelAUTOR;
    private javax.swing.JLabel jLabelCLIENTE;
    private javax.swing.JLabel jLabelCODIGO;
    private javax.swing.JLabel jLabelCODPELICULA;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDNICLIENTE;
    private javax.swing.JLabel jLabelFECHAALQUILADA;
    private javax.swing.JLabel jLabelFECHADEVOLUCION;
    private javax.swing.JLabel jLabelNOMBRE;
    private javax.swing.JLabel jLabelPELICULA;
    private javax.swing.JLabel jLabelTITULO;
    private javax.swing.JList<String> jListAlquileres;
    private javax.swing.JList<String> jListClientes;
    private javax.swing.JList<String> jListPeliculas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPaneLISTA;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1CAJA;
    private javax.swing.JTextField jTextFielANIO;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldAPELLIDOS;
    private javax.swing.JTextField jTextFieldBUSCAR;
    private javax.swing.JTextField jTextFieldCODIGO;
    private javax.swing.JTextField jTextFieldCODPELICULA;
    private javax.swing.JTextField jTextFieldDIRECTOR;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDNICLIENTE;
    private javax.swing.JTextField jTextFieldEDAD;
    private javax.swing.JTextField jTextFieldFECHAALQUILADA;
    private javax.swing.JTextField jTextFieldFECHADEVOLUCION;
    private javax.swing.JTextField jTextFieldGENERO;
    private javax.swing.JTextField jTextFieldNOMBRE;
    private javax.swing.JTextField jTextFieldTITULO;
    // End of variables declaration//GEN-END:variables

}
